In [5]:
import torch
import torch.nn as nn
import numpy as np

x_data = np.array([[0.1, 2.3, 1.5]], dtype=np.float32)
x_data = torch.from_numpy(x_data)

linear = nn.Linear(3, 1)

sign_hypothesis = torch.sign(linear(x_data))
sigmoid_hypothesis = torch.sigmoid(linear(x_data))
relu_hypothesis = torch.relu(linear(x_data))

In [6]:
sign_hypothesis

tensor([[1.]], grad_fn=<SignBackward>)

In [7]:
sigmoid_hypothesis

tensor([[0.8830]], grad_fn=<SigmoidBackward>)

In [8]:
relu_hypothesis

tensor([[2.0215]], grad_fn=<ReluBackward0>)